# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventario', models.IntegerField()),
                ('Prestado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Isbn', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=60)),
                ('Autor', models.CharField(max_length=60)),
                ('Fecha_ingreso', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('Id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_prestamo', models.DateTimeField()),
                ('Fecha_devolucion', models.DateTimeField(blank=True)),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Fecha_nac', models.DateTimeField()),
                ('Estado_moroso', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Socio'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Copia'),
        ),
        migrations.AddField(
            model_name='copia',
            name='Isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Libro'),
        ),
    ]
