# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='Fecha_devolucion',
        ),
        migrations.AlterField(
            model_name='copia',
            name='Inventario',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Estado',
            field=models.CharField(default='Pendiente', max_length=15),
        ),
    ]
