# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_auto_20171113_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copia',
            name='id',
        ),
        migrations.AlterField(
            model_name='copia',
            name='Inventario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Fecha_prestamo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='socio',
            name='Fecha_nac',
            field=models.DateField(),
        ),
    ]
